language: java

jdk:
- oraclejdk7


script: ./gradlew -q clean check jar de distTar installApp
after_script:
  - test -f ./build/libs/de.jar
  - test -f ./build/libs/pxl-deserver.jar
  - test -f ./build/distributions/de.tar

install: /bin/true