language: java

jdk:
- oraclejdk7

before_script:
  - if test $(TRAVIS_BRANCH) == "prod"; then BRANCH="prod"; fi
script:
  - ./gradlew -q clean check jar de distTar installApp


after_script:
  - test -f ./build/libs/de.jar
  - test -f ./build/libs/pxl-deserver.jar
  - test -f ./build/distributions/de.tar

deploy:
  - provider: s3
    access_key_id: AKIAIMEUE7V64YWR6OAQ
    secret_access_key:
      secure: QTEHzGhp2mr3/QL4hGNYQl2Yrvf4eDouyMtEYSy+9jsyRB0XsxV1YxA2bWhDrhqOXg8firA42dJq86tg2ZqJm7UMf5eEP58C9EhW/oqhww76EAoYFbX+Wj0wlQDX3SSoaPHGY+0dY1IlgCak63Z5Yut9n9KN/MQLBVtz50KBW+k=
    bucket: pixelle-salt/s3/pixelle-de-java/prod
    file: ./build/libs/pxl-deserver.jar
    on:
      branch: prod
  - provider: s3
    access_key_id: AKIAIMEUE7V64YWR6OAQ
    secret_access_key:
      secure: QTEHzGhp2mr3/QL4hGNYQl2Yrvf4eDouyMtEYSy+9jsyRB0XsxV1YxA2bWhDrhqOXg8firA42dJq86tg2ZqJm7UMf5eEP58C9EhW/oqhww76EAoYFbX+Wj0wlQDX3SSoaPHGY+0dY1IlgCak63Z5Yut9n9KN/MQLBVtz50KBW+k=
    bucket: pixelle-salt/s3/pixelle-de-java/dev
    file: ./build/libs/pxl-deserver.jar
    on:
      branch: master
