language: go
go:
- 1.3

before_install:
  - cp .netrc ~
  - chmod 600 .netrc

install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.deb
  - sudo dpkg -i elasticsearch-1.3.1.deb
  - sudo service elasticsearch start

script:
  - go get ./...
  - go test -v ./...

notifications:
  webhooks: http://ops.pxlad.io/webhooks/travis

branches:
  only:
    - master
    - prod
