language: go
go:
- 1.3

before_install:
- travis env set CI_USER_TOKEN  da69cb58c5766116055c0fdd1045e95ce7d6c627 --private -r dailymotion/pixelle-analytics-consumer
- echo "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- cat ~/.netrc

install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.deb
  - sudo dpkg -i elasticsearch-1.2.1.deb
  - sudo service elasticsearch start

script:
  - go get ./...
  - go test -v ./...

notifications:
  webhooks: http://ops.pxlad.io/webhooks/travis

branches:
  only:
    - master
    - prod
