language: java
jdk:
- oraclejdk7
script:
- ./gradlew -q clean check jar de distTar installApp
- ls -lRr .
after_script:
- test -f ./build/libs/de.jar
- test -f ./build/libs/pxl-deserver.jar
- test -f ./build/distributions/de.tar
deploy:
  - provider: s3
    access_key_id: AKIAIMEUE7V64YWR6OAQ
    secret_access_key:
      secure: mYlbJK+zPS+KyBrbdbYBXgaEEk8IKn8Ius4fBZSW6LL+BQEbd6Zx7gyPjWBmjvNjXCjeqhMHbjh3Q0fALjOEeb52vd6gFQ2M0jyz2M0gfq+zWX2J2SpFB1XHoE53qoeFp4ARLV+RnMBWDQ2+ruvtWvJ0iTUTsxUyVzM/f16cEa4=
    local-dir: ./build/libs
    bucket: pixelle-salt/s3/pixelle-de-java/dev
    acl: private
    on:
      repo: dailymotion/pixelle-de
      branch: master
  - provider: s3
    access_key_id: AKIAIMEUE7V64YWR6OAQ
    secret_access_key:
      secure: mYlbJK+zPS+KyBrbdbYBXgaEEk8IKn8Ius4fBZSW6LL+BQEbd6Zx7gyPjWBmjvNjXCjeqhMHbjh3Q0fALjOEeb52vd6gFQ2M0jyz2M0gfq+zWX2J2SpFB1XHoE53qoeFp4ARLV+RnMBWDQ2+ruvtWvJ0iTUTsxUyVzM/f16cEa4=
    local-dir: ./build/libs
    bucket: pixelle-salt/s3/pixelle-de-java/prod
    acl: private
    on:
      repo: dailymotion/pixelle-de
      branch: prod

