language: java
jdk:
- oraclejdk7

script:
- ./gradlew -q check jar de distTar installApp

after_script:
- test -f ./build/libs/de.jar
- test -f ./build/libs/pxl-deserver.jar
- test -f ./build/distributions/de.tar

cache:
  directories:
  - $HOME/.gradle/caches/

deploy:
  - provider: s3
    access_key_id: AKIAIMEUE7V64YWR6OAQ
    secret_access_key:
      secure: aOp+yZ5mF25HU6zELWfqam/AsaqBbl1SQ14T9ert0brQ37Ol24jBXM53MLfzkL6m03apSSJrLaKexEIKCeScOqoCdp+TctXqXRrFFGWMgd3QYqv5+wLbtHpkuSPX928KpepZMTu1JQUeahVaYwqeMLYeKIbB4TF6RdlCcNNma+M=
    bucket: pixelle-salt/s3/pixelle-de-java/dev
    acl: private
    skip_cleanup: true
    local-dir: ./build/distributions/
    on:
      repo: dailymotion/pixelle-de
      branch: master
  - provider: s3
    access_key_id: AKIAIMEUE7V64YWR6OAQ
    secret_access_key:
      secure: aOp+yZ5mF25HU6zELWfqam/AsaqBbl1SQ14T9ert0brQ37Ol24jBXM53MLfzkL6m03apSSJrLaKexEIKCeScOqoCdp+TctXqXRrFFGWMgd3QYqv5+wLbtHpkuSPX928KpepZMTu1JQUeahVaYwqeMLYeKIbB4TF6RdlCcNNma+M=
    bucket: pixelle-salt/s3/pixelle-de-java/prod
    local-dir: ./build/distributions/
    acl: private
    skip_cleanup: true
    on:
      repo: dailymotion/pixelle-de
      branch: prod
