language: go
go:
- 1.3

before_install:
- echo "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc


install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.deb
  - sudo dpkg -i elasticsearch-1.2.1.deb
  - sudo service elasticsearch start

script:
  - go get ./...
  - go test -v ./...

notifications:
  webhooks: http://ops.pxlad.io/webhooks/travis

branches:
  only:
    - master
    - prod
