language: java
jdk:
- oraclejdk7

script:
- ./gradlew -q check jar de distTar installApp

after_script:
- test -f ./build/libs/de.jar
- test -f ./build/libs/pxl-deserver.jar
- test -f ./build/distributions/de.tar

cache:
  directories:
  - $HOME/.gradle/caches/

deploy:
  - provider: s3
    access_key_id: AKIAIJN4I4KQTPPM45WQ
    secret_access_key:
      secure: IBQdVvLarxSaida1dr8agaBsL0kF2uJYCmuv1FRpFKlhHrCKhBJEFFwNzRHv4gm93OF0R7YxtoHe3D0lQMkxDMdoXMrdmeFX297cc9SVYNIG0/RWrq4pofAZxkEZy0FoZINQ3Ra2LLuUAyFxpuumpPFcSEuUpb/ddqmyC/Gw+rA=
    bucket: pixelle-salt/s3/pixelle-de-java/dev
    acl: private
    skip_cleanup: true
    local-dir: ./build/distributions/
    on:
      repo: dailymotion/pixelle-de
      branch: master
  - provider: s3
    access_key_id: AKIAIJN4I4KQTPPM45WQ
    secret_access_key:
      secure: IBQdVvLarxSaida1dr8agaBsL0kF2uJYCmuv1FRpFKlhHrCKhBJEFFwNzRHv4gm93OF0R7YxtoHe3D0lQMkxDMdoXMrdmeFX297cc9SVYNIG0/RWrq4pofAZxkEZy0FoZINQ3Ra2LLuUAyFxpuumpPFcSEuUpb/ddqmyC/Gw+rA=
    bucket: pixelle-salt/s3/pixelle-de-java/prod
    local-dir: ./build/distributions/
    acl: private
    skip_cleanup: true
    on:
      repo: dailymotion/pixelle-de
      branch: prod
